name: codecrafters-bittorrent
version: 0.1.0.0
license: BSD3

dependencies:
  - base >= 4.19 && < 5
  - aeson # for JSON
  - network-simple # establish a simple TCP network
  - bytestring # useful to send bytes over the network
  - network # required when using bytestring
  - text # use Text rather than String
  - containers # may help with the database structure and debugging
  - time # may help with the expiry function
  - async # may help with concurrency
  - mtl # may help with structuring
  # Parsing libs
  - megaparsec
  - parser-combinators
  - parsec
  - attoparsec
  - cryptonite
  - memory
  - http-client
  - http-client-tls
  - http-types
  - random

library:
  source-dirs: src
  exposed-modules:
    - Types
    - Bencode
    - HttpReq
    - Torrent
    - Tracker
    - Peer

executables:
  codecrafters-bittorrent-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - codecrafters-bittorrent
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
